services:
  - type: web
    name: browser-daw-nexa
    runtime: node
    plan: free
    branch: main
    buildCommand: yarn install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
