services:
  - type: web
    name: browser-daw-nexa
    runtime: node
    plan: free
    repo: https://github.com/coltellislong/browser-daw-nexa
    branch: main
    rootDir: .
    buildCommand: npm install --omit=dev
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
